export const categories = [
    {
      id: 1,
      title: "Salud",
      icon: "mdi mdi-hospital-building",
      showSubtopics: false,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      subtopics: [
        {
          id: 1,
          title: "Salud Primaria",
          pob_value: 20,
          total_value: 50,
          description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          grid: [
            ["green", "green", "green", "green", "red", "red"],
            ["green", "red", "red", "red", "green", "red"],
            ["green", "red", "red", "green", "red", "red"],
            ["red", "red", "green", "red", "green", "red"],
            ["green", "red", "red", "red", "red", "red"],
          ],
        },
      ],
      color: "#c93b30",
    },
    {
      id: 2,
      title: "Educación",
      icon: "mdi mdi-school",
      showSubtopics: false,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      subtopics: [
        {
          id: 1,
          title: "Educación Básica",
          pob_value: 80,
          total_value: 90,
          description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          grid: [
            ["red", "red", "green", "red", "green", "red"],
            ["red", "green", "red", "green", "red", "green"],
            ["green", "green", "red", "red", "red", "red"],
            ["green", "green", "red", "green", "red", "green"],
            ["red", "red", "green", "red", "red", "red"],
          ],
        },
        {
          id: 2,
          title: "Educación Media",
          pob_value: 75,
          total_value: 82,
          description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          grid: [
            ["red", "green", "red", "green", "red", "green"],
            ["green", "red", "red", "green", "red", "green"],
            ["red", "red", "green", "red", "green", "green"],
            ["green", "green", "red", "red", "red", "red"],
            ["red", "red", "green", "red", "red", "green"],
          ],
        },
      ],
      color: "#58329c",
    },
    {
      id: 3,
      title: "Cultura",
      icon: "mdi mdi-theater",
      showSubtopics: false,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      subtopics: [
        {
          id: 1,
          title: "Bibliotecas",
          pob_value: 50,
          total_value: 63,
          description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          grid: [
            ["green", "green", "green", "green", "red", "green"],
            ["red", "red", "green", "green", "red", "red"],
            ["green", "red", "green", "red", "green", "green"],
            ["red", "green", "red", "red", "red", "red"],
            ["green", "green", "red", "green", "red", "red"],
          ],
        },
        {
          id: 2,
          title: "Sedes Sociales",
          pob_value: 65,
          total_value: 58,
          description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          grid: [
            ["red", "red", "green", "red", "green", "red"],
            ["green", "green", "red", "green", "red", "green"],
            ["green", "red", "green", "red", "green", "red"],
            ["green", "green", "red", "green", "red", "green"],
            ["red", "red", "green", "red", "green", "red"],
          ],
        },
      ],
      color: "#354394"
    },
    {
      id: 4,
      title: "Deporte",
      icon: "mdi mdi-football",
      showSubtopics: false,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      subtopics: [
        {
          id: 1,
          title: "Gimnasios",
          pob_value: 30,
          total_value: 67,
          description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          grid: [
            ["red", "green", "red", "red", "green", "red"],
            ["green", "red", "red", "green", "red", "green"],
            ["green", "green", "red", "red", "red", "red"],
            ["green", "green", "red", "green", "green", "green"],
            ["red", "green", "red", "red", "green", "green"],
          ],
        },
        {
          id: 2,
          title: "Multicanchas",
          pob_value: 40,
          total_value: 35,
          description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          grid: [
            ["red", "red", "green", "red", "red", "red"],
            ["red", "green", "red", "green", "red", "green"],
            ["green", "green", "green", "red", "green", "red"],
            ["red", "red", "green", "green", "green", "red"],
            ["green", "red", "red", "red", "green", "red"],
          ],
        },
        {
          id: 3,
          title: "Canchas de Fútbol",
          pob_value: 75,
          total_value: 60,
          description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          grid: [
            ["red", "green", "red", "green", "green", "red"],
            ["red", "red", "green", "green", "red", "green"],
            ["green", "green", "red", "red", "red", "red"],
            ["green", "green", "red", "red", "red", "red"],
            ["red", "red", "red", "green", "green", "green"],
          ],
        },
      ],
      color: "#1172bf",
    },
    {
      id: 5,
      title: "Áreas Verdes",
      icon: "mdi mdi-forest",
      showSubtopics: false,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      subtopics: [
        {
          id: 1,
          title: "Áreas Verdes",
          pob_value: 75,
          total_value: 80,
          description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          grid: [
            ["green", "red", "green", "red", "green", "red"],
            ["green", "green", "red", "green", "red", "green"],
            ["green", "red", "green", "red", "green", "red"],
            ["green", "green", "red", "green", "red", "green"],
            ["red", "red", "green", "red", "green", "red"],
          ],
        },
        {
          id: 2,
          title: "Parques",
          pob_value: 75,
          total_value: 56,
          description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          grid: [
            ["green", "red", "green", "red", "green", "red"],
            ["green", "green", "red", "green", "red", "green"],
            ["green", "green", "green", "red", "green", "red"],
            ["green", "green", "red", "green", "red", "green"],
            ["red", "red", "green", "red", "green", "red"],
          ],
        },
      ],
      color: "#3a853d",
    },
    {
      id: 6,
      title: "Movilidad",
      icon: "mdi mdi-bike",
      showSubtopics: false,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      subtopics: [
        {
          id: 1,
          title: "Subtopic 6.1",
          pob_value: 75,
          total_value: 89,
          description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          grid: [
            ["green", "red", "green", "red", "green", "red"],
            ["green", "green", "green", "green", "red", "green"],
            ["green", "red", "green", "red", "green", "red"],
            ["green", "green", "red", "green", "red", "green"],
            ["red", "red", "green", "red", "green", "red"],
          ],
        },
        {
          id: 2,
          title: "Subtopic 6.2",
          pob_value: 54,
          total_value: 78,
          description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          grid: [
            ["green", "green", "green", "red", "green", "red"],
            ["green", "green", "red", "green", "red", "green"],
            ["green", "red", "green", "red", "green", "red"],
            ["green", "red", "green", "red", "green", "red"],
            ["red", "red", "green", "red", "green", "red"],
          ],
        },
      ],
      color: "#a35105",
    }
]